### ISSUE TITLE
loaders is undefined for ExternalModule

### ISSUE THREAD

**Issue by rnaud** [stephencookdev/speed-measure-webpack-plugin#11]
Hello!
Getting the error `TypeError: Cannot read property 'length' of undefined` from `speed-measure-webpack-plugin/utils.js:50` when I have an `externals` key in my webpack.config.js

```
  externals: {
    analytics: 'analytics',
    jquery: 'jQuery'
  }
```

It seems `ExternalModule` is wrapping `NormalModule` inside the issuer key and the top level ExternalModule doesn't have a `loaders` key.

**Comment by stephencookdev** [comment]
Ah, yeah annoyingly I just spotted this in my local v1 branch

I should be able to push a fix for this tomorrow morning

**Comment by stephencookdev** [comment]
Okay, I've just merged https://github.com/stephencookdev/speed-measure-webpack-plugin/pull/13

That should fix this for you. Let me know!

**Comment by rnaud** [comment]
This is fixed as well for me in our latest tests, thanks!
