### ISSUE TITLE
Use webpack-chain to do webpack configuration in vue.config.js, so how to use speed-measure-webpack-plugin plugin?

### ISSUE THREAD

**Issue by GitHubGanKai** [stephencookdev/speed-measure-webpack-plugin#121]
According to the configuration of speed-measure-webpack-plugin, all the plugins are wrapped, but if you use webpack-chain, can you not use this plugin?

[](https://stackoverflow.com/questions/61380714/use-webpack-chain-to-do-webpack-configuration-in-vue-config-js-so-how-to-use-sp)

**Comment by raypatterson** [comment]
Based on this example

https://github.com/stephencookdev/speed-measure-webpack-plugin/blob/24052675160ceaf42f53d06e3da538ecf04e9e81/examples/webpack-merge.config.js#L38

I was able apply with:

```javascript
import Config from "webpack-chain";
import SpeedMeasurePlugin from "speed-measure-webpack-plugin";

const webpackChain = new Config();
const smp = new SpeedMeasurePlugin();

export default smp.wrap(webpackChain.toConfig());
```

**Comment by GitHubGanKai** [comment]
thank you ！
