### ISSUE TITLE
Wrong time listing for plugins that inject into "after-emit"

### ISSUE THREAD

**Issue by rnaud** [stephencookdev/speed-measure-webpack-plugin#14]
Hey, it's me again :)

Tested this plugin in production, it seems it's not working with plugins that are injecting themselves into `after-emit` callbacks. It's reporting just the init time for these plugins at around 1ms.

## Plugins impacted:
* https://github.com/webpack-contrib/s3-plugin-webpack
* https://github.com/thredup/rollbar-sourcemap-webpack-plugin

**Comment by stephencookdev** [comment]
Nice, thanks for raising :)

Yeah, poking around a bit it looks like it's because of the callback inside the `after-emit` hook they're sending. Should be a relatively easy fix, I'll try to get something sorted out soon

**Comment by stephencookdev** [comment]
Okay cool, so I noticed a couple of other similar issues too.

Does 0.3.2 fix this for you?

**Comment by rnaud** [comment]
Hmmmm, it seems like this is now making my builds hang forever and eventually timeout.

**Comment by stephencookdev** [comment]
Ahhh, nightmare! :/

Okay, I'm going to try and mess around with those 2 plugins you mentioned - but any other info you can provide to help me debug would be appreciated

**Comment by stephencookdev** [comment]
Okay, I hopefully spotted the issue that was causing the builds to hang (I wasn't mirroring the plugin callbacks correctly)

v0.3.3 will hopefully sort you?

**Comment by rnaud** [comment]
That worked!

Thanks a lot @stephencookdev 👍 
Here is the full output I got: 

```
18:59:37        General output time took 8m 23.6s
18:59:37        Plugin HardSourceWebpackPlugin took 11m 30.9s
18:59:37        Plugin UglifyJsPlugin took 1m 41.1s
18:59:37        Plugin S3Plugin took 1m 29.4s
18:59:37        Plugin ExtractTextPlugin took 58.9s
18:59:37        Plugin ProvidePlugin took 6.5s
18:59:37        Plugin RollbarSourceMapPlugin took 1.8s
18:59:37        Plugin AssetsWebpackPlugin took 372ms
18:59:37        Plugin DefinePlugin took 24ms
18:59:37        Plugin ModuleConcatenationPlugin took 24ms
18:59:37        Plugin CommonsChunkPlugin took 2ms
18:59:37        Loaders css-loader,sass-loader took 2m 24.7s
18:59:37        Loaders babel-loader took 1m 17.9s
18:59:37        Loaders extract-text-webpack-plugin,style-loader,css-loader,sass-loader took 59s
18:59:37        Loaders (none) took 28.8s
18:59:37        Loaders coffee-loader,cjsx-loader took 13.4s
18:59:37        Loaders coffee-loader took 5.5s
18:59:37        Loaders file-loader took 4.4s
18:59:37        Loaders json-loader took 864ms
```

And here is what I used to get the output. I could not rely on the `human` template since the ANSI colors were creating unreadable text in jenkins

```
const wrappedPlugins = {}
mergedExports.plugins.forEach(function(plugin) {
  wrappedPlugins[plugin.constructor.name] = plugin
})
mergedExports.plugins = SpeedMeasurePlugin.wrapPlugins(wrappedPlugins, {outputFormat: function(outputObj) {
  if (outputObj.misc) {
    console.log(`General output time took ${prettyMs(outputObj.misc.compileTime)}`)
  }
  if (outputObj.plugins) {
    Object.keys(outputObj.plugins)
      .sort(
        (name1, name2) => outputObj.plugins[name2] - outputObj.plugins[name1]
      )
      .forEach(pluginName => {
        console.log(`Plugin ${pluginName} took ${prettyMs(outputObj.plugins[pluginName])}`)
      });
  }
  if (outputObj.loaders) {
    outputObj.loaders.build
      .sort((obj1, obj2) => obj2.activeTime - obj1.activeTime)
      .forEach(loaderObj => {
        console.log(`Loaders ${loaderObj.loaders.join(",")} took ${prettyMs(loaderObj.activeTime)}`)
      });
  }
}})
module.exports = mergedExports
```

**Comment by stephencookdev** [comment]
Nice! :)

I've added https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/16 to add in colour-stripping support as a documented option

FWIW you could also get the output working for your Jenkins config by doing something like

```
const { stripColours } = require("speed-measure-webpack-plugin/colours");
...
SpeedMeasurePlugin.wrapPlugins(wrappedPlugins, {
  outputTarget: output => console.log(stripColours(output)),
});
```

but yeah, that's not a documented feature. In v1 I'll add some option like `{ color: true/false }`
