### ISSUE TITLE
Optimising modules with no loaders

### ISSUE THREAD

**Issue by ersel** [stephencookdev/speed-measure-webpack-plugin#43]
Hi @stephencookdev ,

Firstly, thanks for developing this plugin. I have a question regarding the `Modules with no loaders` output.

Our current webpack config produces the following output:

```
 SMP  ⏱  Loaders
babel-loader took 8.56 secs
  module count = 821
modules with no loaders took 5.3 secs
  module count = 104
```

I was wondering if and how we can optimize our configuration to skip those _104_ modules with no loaders?

**Comment by stephencookdev** [comment]
Hey @ersel :)

So "modules with no loaders" are any JS file that webpack just loads in. Probably your bulk of files here is coming from `node_modules`

I'll try and add a feature in the future to help visualise what all of these files are that are taking time. But until then, if you download [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) you should be able to see all of your dependencies (sorted by their size). Cutting down on needlessly large dependencies will help reduce this number!

**Comment by ersel** [comment]
Thanks Steve, a list of files would be very helpful to see. I will try webpack-bundle-analyzer.

Maybe CLI could even give some recommendations on how to optimize different loaders.

e.g:
node-sass taking too long? see fast-sass-loader
babel-loader taking too long? try setting `cacheDirectory` to true if not set already etc...

**Comment by Herz3h** [comment]
So how to determine which files are loaded ? my "modules with no loaders" takes 30sec, I would like to optimize if possible.

**Comment by yizhengfeng-jj** [comment]
> Hey @ersel :)
> 
> So "modules with no loaders" are any JS file that webpack just loads in. Probably your bulk of files here is coming from `node_modules`
> 
> I'll try and add a feature in the future to help visualise what all of these files are that are taking time. But until then, if you download [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) you should be able to see all of your dependencies (sorted by their size). Cutting down on needlessly large dependencies will help reduce this number!

Hello, has this function been implemented, and is there any documentation?
