### ISSUE TITLE
Is this compatible with Webpack 4.16.5?

### ISSUE THREAD

**Issue by vdh** [stephencookdev/speed-measure-webpack-plugin#48]
I tried installing this today, but Webpack just hung indefinitely and produced no output.

I didn't have time to debug it any further, and my config is a bit of a mess, so I just wanted to check if there's anything in general that would cause a silent hang like this?

**Comment by stephencookdev** [comment]
It shouldn't do - the plugin should be fine with webpack 4. I'd need a bit more info about your config to debug why the plugin is causing your build to hang

**Comment by stephencookdev** [comment]
Will close this for the time being. Please reopen with some config etc. if you're still seeing the issue ☺️

**Comment by theKashey** [comment]
Same thing :( Hangs with webpack 4.19 + awesome-tsloader

**Comment by vdh** [comment]
It's close to impossible to debug my config without sending my entire project, and there's nothing for me to prune it down to because it's just a silent hang.
