### ISSUE TITLE
Combine with cpuprofile-webpack-plugin

### ISSUE THREAD

**Issue by jantimon** [stephencookdev/speed-measure-webpack-plugin#70]
Hey,

I started an experiment which does the same thing what you are trying to do:

https://github.com/jantimon/cpuprofile-webpack-plugin

The difference is that it uses the cpuprofile and therefore has more information about garbage collection and also better tracing of asynchronous code:

<img width="558" alt="cpu-profile" src="https://user-images.githubusercontent.com/4113649/51028830-e7cfa900-1594-11e9-9700-605fad0dfec6.png">

You can see a preview of the report here: https://jantimon.github.io/cpuprofile-webpack-plugin/

Maybe we can combine both plugins? :)

**Comment by stephencookdev** [comment]
Hey - really cool plugin :heart_eyes: I need to take a look through the source code properly

What do you mean by "combine" the plugins?

**Comment by jantimon** [comment]
I don’t have a concrete idea on it but both plugins try to help making webpack builds faster so maybe we can reuse some of the ideas :)

**Comment by stephencookdev** [comment]
(closing this because it's just been sat open for ages - but feel free to ping me on Twitter if you want to chat ideas around this 🙂)
