### ISSUE TITLE
Example for Usage in Webpack Encore

### ISSUE THREAD

**Issue by julia-r** [stephencookdev/speed-measure-webpack-plugin#77]
Can I use this in [Webpack Encore](https://www.npmjs.com/package/@symfony/webpack-encore)? Can anyone show me how I would implement it there?

**Comment by stephencookdev** [comment]
There should be no reason this wouldn't work

Just something like this should do it:

```javascript
module.exports = smp.wrap(Encore.getWebpackConfig());
```

**Comment by julia-r** [comment]
That works, thank you!
