### ISSUE TITLE
webpack v1, v2 support

### ISSUE THREAD

**Issue by stephencookdev** [stephencookdev/speed-measure-webpack-plugin#8]
Currently only webpack v3 has been tested

webpack v1 and v2 should be tested, and if plausible, given support for

**Comment by stephencookdev** [comment]
Added in ce354bdaabc5e0d12e7e8acac37f123648230edd

**Comment by RinkAttendant6** [comment]
This wasn't added correctly. Now the plugin only indicates compatibility with v1.

The peerDependency should be `^1 || ^2 || ^3` to indicate compatibility with all three versions, if the plugin is indeed compatible with all of them

**Comment by stephencookdev** [comment]
Ah, you're entirely right. I must have accidentally missed the compiler warnings when I merged this change :slightly_frowning_face: 

I'll raise a fix for this in a mo @RinkAttendant6 - thanks for raising :slightly_smiling_face: 

But yes, this plugin is compatible with v1/2/3 (not 4 yet)

**Comment by stephencookdev** [comment]
Fixed in 12124473825f1222c96fc0ccdf613d5107d011cf
