### ISSUE TITLE
Build times are significantly longer using SMP

### ISSUE THREAD

**Issue by daleyjem** [stephencookdev/speed-measure-webpack-plugin#82]
I work on a project with multiple webpack configs (server & client) and the build times take a while... the reason I started looking into SMP to begin with.

Now with SMP, my build times have exactly doubled (6 mins --> 12 mins).

I like the idea of this tool for logging CI/CD build times, but it seems as though the intended purpose is occasional, manual use.

If I were curious enough to contribute to the project, where might I start trying to make optimizations so that the wrapper did not significantly increase total Webpack build times as much as they do?

**Comment by daleyjem** [comment]
I wonder if getting the prettified loader names could be done after the the process and just concat them during.

`/full/path/to/node_modules/some-loader/src/index.js?/full/path/to/node_modules/other-loader/dist/index.js`

**Comment by daleyjem** [comment]
Also, don't you want to tap into `thisCompilation`? I could be wrong on this, but `compilation` is going to fire multiple times within the plugin, whereas `thisCompilation` only once.

**Comment by stephencookdev** [comment]
Hey @daleyjem thanks for your issue.

SMP definitely isn't meant to _double_ the compilation the time, and it's not something I've noticed in my projects. However, it does necessarily need to increase the compilation time, just because measuring takes time.

Some things could definitely be optimised! The prettifying of the loader names is a good example.

Please feel free to suggest some PRs, as long as the functional tests are passing, then the optimisations are probably all good

**Comment by jrnail23** [comment]
FWIW, I just measured my production builds on a somewhat smallish app, and builds that take an average of 11.1 seconds without SMP take 11.5 seconds with SMP, so it's only adding ~3.5% to my build time, which is totally acceptable in my book.

@daleyjem, perhaps there's something weird going on with one of your plugins (or something else in your webpack config) that's causing it to slow down significantly.  Doubling your build time is definitely not a typical result.

**Comment by avin-kavish** [comment]
@daleyjem exactly how big is your project to require 6mins of build time? The last application I compiled that took that long to build was openCV with an output size of 4GB. I can't imagine a web project being that big.

**Comment by daleyjem** [comment]
@avin-kavish I work for a very large company. We have 200+ of our own packages that require just about every Webpack loader under the sun (for CSS/image imports, etc.)

**Comment by avin-kavish** [comment]
Doesn't that solve the problem? Build each package separately, and use a private npm registry for sharing and versioning your internal packages.

**Comment by daleyjem** [comment]
That's currently in the works... Pre transpilation. As of now though, every package is transpiled in a single build. I wanted to use SMP to show how time would be saved with pre transpilation.

**Comment by zdila** [comment]
Build time of my project was 1m 25s. After adding SMP I had to Ctrl+C after 19 minutes.
