### ISSUE TITLE
Loader name extraction not compatible with Windows

### ISSUE THREAD

**Issue by rjgotten** [stephencookdev/speed-measure-webpack-plugin#84]
https://github.com/stephencookdev/speed-measure-webpack-plugin/blob/add1954bdc91d7c71c01105a43473267455b78e3/loader.js#L9

https://github.com/stephencookdev/speed-measure-webpack-plugin/blob/469644031367772be9c2604afbcae7987cf05232/utils.js#L55

These regexes only work properly for systems that use forward slashes for local filesystem paths. Windows uses back slashes. 

You can use the `[\\/]` character set to represent both kinds of directory separators instead.

**Comment by stephencookdev** [comment]
This should be fixed in 1.3.3
