### ISSUE TITLE
Some loaders appear more than once

### ISSUE THREAD

**Issue by AILINGANGEL** [stephencookdev/speed-measure-webpack-plugin#88]
Hi, when I use this plugin ,the output shows some loaders , like scss-loader,  appear many times, so why this happens, what does it mean? I appreciate anyone's help.

screenshot:
![image](https://user-images.githubusercontent.com/28471649/62668352-2d831180-b9be-11e9-97b9-e8e2653053e0.png)

**Comment by stephencookdev** [comment]
This has been raised a couple of times before. Basically:

This is expected output, but it is just inherently confusing. The way webpack runs, the different loaders run in different configurations, and without setting SMP's `granularLoaderData` option, what SMP outputs is also, unfortunately, quite confusing!

I've raised https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/51 to hopefully address the confusion
