### ISSUE TITLE
webpack v4 support

### ISSUE THREAD

**Issue by stephencookdev** [stephencookdev/speed-measure-webpack-plugin#9]
webpack v4 compatibility needs to be added (as this plugin won't work properly with v4 atm)

**Comment by stephencookdev** [comment]
I've looked at the webpack v4 specs, and have a plan to add SMP support.

I want to add a test-suite, though, before adding more webpack versions - so we can make sure things stay working

**Comment by SirWindfield** [comment]
Strange, I just added it to my webpack 4 project and it worked without any problems.

**Comment by stephencookdev** [comment]
So the changes webpack 4 made are such that depending on the plugins and loaders, either everything will be fine, or it will be fine but inaccurate, or it will break.
So yes, for some configs you might get away with it - but it's not yet fully supported

**Comment by stephencookdev** [comment]
I've raised a PR for this now: https://github.com/stephencookdev/speed-measure-webpack-plugin/pull/31

I want to run a lot more testing before merging + releasing. I'll aim to release during the coming week, but if anyone wanting v4 support could check out SMP on that branch and let us know if you encounter any issues with it - that'd be much appreciated!
